### ISSUE TITLE
 No module named 'click'

### ISSUE THREAD

**Issue by madtoby555** [AdminWhaleFall/SMSBoom#3]
运行pipenv run python3.8 smsboom.py 报错 提示 No module named 'click'
OS:ubuntu16.0
python version:3.8

**Comment by madtoby555** [comment]
另外建议设置编码为utf-8

**Comment by AdminWhaleFall** [comment]
请问运行 `pipenv install` 安装依赖包了吗 ？  
此错误表明 `click` 模块没有正确安装，需要手动激活虚拟环境 `pipenv shell` 再 `pip install click` 手动安装。

**Comment by madtoby555** [comment]
> 装依赖包了吗 ？
> 此错误表明 `click` 模块没有正确安装

**Comment by madtoby555** [comment]
> 解决了 使用的是pipenv install --dev

另外之前运行过`pipenv install`
