### ISSUE TITLE
運行錯誤

### ISSUE THREAD

**Issue by SiMaLaoShi** [AdminWhaleFall/SMSBoom#4]
![image](https://user-images.githubusercontent.com/28924681/164354483-021d5a87-d741-4ee7-8759-cdfae9161ee9.png)

**Comment by AdminWhaleFall** [comment]
可能是以下几种情况:  
- 网络请求过于密集，触发接口风控。
- 接口失效。  
- 本机网络问题，部分接口仅限于中国大陆地区请求，若有需要请尝试使用 proxy
