### ISSUE TITLE
 ERROR - 拉取更新失败:EOF occurred in violation of protocol (_ssl.c:1125)请多尝试几次!

### ISSUE THREAD

**Issue by CrossguoAND** [AdminWhaleFall/SMSBoom#5]
请问这个要怎么解决呢？感谢回答
![image](https://user-images.githubusercontent.com/76768087/164889097-084e9fd7-8e6e-4b5f-a944-2ca491ac41b4.png)

**Comment by AdminWhaleFall** [comment]
参见 issue [#2](https://github.com/AdminWhaleFall/SMSBoom/issues/2#issuecomment-1095876994)  
关闭 proxy 软件重试即可。

**Comment by 1437879650** [comment]
![image](https://user-images.githubusercontent.com/59512313/182921442-21dd5c10-a5fb-435f-ba5d-af60acc1d599.png)请问这个要怎么解决呢？感谢回答

**Comment by YangBo1130** [comment]
![image](https://user-images.githubusercontent.com/45474235/196331534-3c6b366d-cd82-4009-b676-eb4f09067922.png)
这个怎么解决

**Comment by YangBo1130** [comment]
![image](https://user-images.githubusercontent.com/45474235/196331635-274c8c62-67b7-40c2-916b-70dcca5793fa.png)
这个要如何解决

**Comment by AROMR** [comment]
关了代理也拉不下来
![image](https://github.com/OpenEthan/SMSBoom/assets/88938017/208fc1b8-7b79-472f-98d7-a42cb198b576)
