### ISSUE TITLE
感谢作者 用来对付骗子挺不错

### ISSUE THREAD

**Issue by lxh1943** [AdminWhaleFall/SMSBoom#6]
666

**Comment by AdminWhaleFall** [comment]
谢谢您对项目的支持，但请注意不要用于违法用途哦。下面我来唱给您听：  

听我说👂👂👂谢谢你🙏🙏🙏因为有你👉👉👉温暖了四季🌈🌈🌈谢谢你🙏🙏🙏感谢有你👉👉👉世界更美丽🌏🌏🌏我要谢谢你🙏🙏🙏因为有你👉👉👉爱常在心底💃💃💃谢谢你 🙏🙏🙏感谢有你🙇‍♀️🙇‍♀️🙇‍♀️把幸福传递.
